In [53]:
import numpy as np
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [54]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [55]:
X = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(X[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [57]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [58]:
model = Sequential()
model.add(Dense(100, input_shape=(4,), activation="relu"))
model.add(Dense(3, activation="softmax"))

In [59]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [60]:
model.fit(X_train, y_train, epochs=20)

Epoch 1/20


4/4 [==============================] - 1s 3ms/step - loss: 1.8490 - accuracy: 0.3250
Epoch 2/20
4/4 [==============================] - 0s 3ms/step - loss: 1.5732 - accuracy: 0.0417
Epoch 3/20
4/4 [==============================] - 0s 2ms/step - loss: 1.3769 - accuracy: 0.0000e+00
Epoch 4/20
4/4 [==============================] - 0s 2ms/step - loss: 1.2576 - accuracy: 0.1333
Epoch 5/20
4/4 [==============================] - 0s 3ms/step - loss: 1.1552 - accuracy: 0.3083
Epoch 6/20
4/4 [==============================] - 0s 3ms/step - loss: 1.1017 - accuracy: 0.3333
Epoch 7/20
4/4 [==============================] - 0s 2ms/step - loss: 1.0576 - accuracy: 0.2000
Epoch 8/20
4/4 [==============================] - 0s 2ms/step - loss: 1.0284 - accuracy: 0.3250
Epoch 9/20
4/4 [==============================] - 0s 2ms/step - loss: 0.9973 - accuracy: 0.3500
Epoch 10/20
4/4 [==============================] - 0s 2ms/step - loss: 0.9655 - accuracy: 0.5417
Epoch 11/20
4/4 [=============================

In [61]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 117ms/step - loss: 0.7072 - accuracy: 0.7667


[0.7072290778160095, 0.7666666507720947]

In [62]:
pred=model.predict(X_test[:10])
print(pred)

1/1 [==============================] - 0s 43ms/step
[[0.08123388 0.3622975  0.5564686 ]
 [0.13299876 0.3702283  0.49677292]
 [0.5923859  0.22528957 0.18232456]
 [0.1743745  0.37279686 0.45282865]
 [0.21844463 0.39421782 0.3873375 ]
 [0.10326049 0.3782359  0.51850355]
 [0.1429949  0.3938962  0.46310893]
 [0.10686679 0.3765452  0.51658803]
 [0.11290445 0.37509173 0.51200384]
 [0.2003371  0.38770694 0.41195595]]


In [63]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 2 0 2 1 2 2 2 2 2]
[2 2 0 1 1 2 2 2 2 1]


In [64]:
for i in p:
    print("Predicted class: {}, Name: {}".format(i,z[i]))

Predicted class: 2, Name: virginica
Predicted class: 2, Name: virginica
Predicted class: 0, Name: setosa
Predicted class: 2, Name: virginica
Predicted class: 1, Name: versicolor
Predicted class: 2, Name: virginica
Predicted class: 2, Name: virginica
Predicted class: 2, Name: virginica
Predicted class: 2, Name: virginica
Predicted class: 2, Name: virginica
